/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/

#define IGNORE_MOD_TAP_INTERRUPT
#define USB_SUSPEND_WAKEUP_DELAY 0

#undef DEBOUNCE
#define DEBOUNCE 5
#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2
#undef USB_POLLING_INTERVAL_MS
#define USB_POLLING_INTERVAL_MS 1

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 6
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 160
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 4
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 80
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 69
#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 7

#define RGB_MATRIX_LED_PROCESS_LIMIT DRIVER_LED_TOTAL
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define RGB_MATRIX_LED_FLUSH_LIMIT 1000

#define CAPS_LOCK_STATUS